### ISSUE TITLE
When using the `by` argument all factorial combinations of the elements must exist in the summary dataset else an error is thrown.

### ISSUE THREAD

**Issue by mikesweeting** [ellessenne/rsimsum#47]
**Is your feature request related to a problem?**
When using the `by` argument all factorial combinations of the elements must exist in the summary dataset else an error is thrown.

But occasionally we are in a situation where not all combinations exist (it may be that certain combinations of the factors are not of interest). In my situation it is that we want to plot just the subset where factor A is not equal to factor B

Below is a contrived situation where we are not interested in settings where ss=100 and esigma=2. This throws an error.
```{r}
nlp.subset <- nlp %>% filter(!(ss==100 & esigma==2))
s.nlp.subset <- rsimsum::simsum(
  data = nlp.subset, estvarname = "b", true = 0, se = "se",
  methodvar = "model", by = c("baseline", "ss", "esigma")
)
```

**Describe the solution you'd like**
It would be great if we could get an nlp plot for only the combination of factors that exist in the dataset that is passed to simsum.

**Describe alternatives you've considered**
Currently I'm unable to use a nlp plot for subsets of settings which are not factorial in nature.

**Comment by mikesweeting** [comment]
Thanks Alessandro, that's great! My only other suggestion might be to remove the "gaps" in the plot, but I don't feel strongly about that. 

Thank you for implementing this.
Mike

**Comment by ellessenne** [comment]
Thanks for the feedback! 

The main reason I have implemented it this way is that it makes it obvious that some scenarios (vs the equivalent fully-factorial design) are missing, and that otherwise the "steps" in the plot look weird at the gaps (and makes it hard to understand, I think, given that the scenario patterns are now broken).

With gaps:

![](https://i.imgur.com/YWC4oBX.png)

Without gaps:

![](https://i.imgur.com/yaeMv2x.png)

The second plot looks much harder to understand from my point of view (and it not immediately obvious that some scenarios are missing). What do you think?

**Comment by mikesweeting** [comment]
I agree. Let's keep it with the gaps. Thanks for implementing!

**Comment by ellessenne** [comment]
Super, thanks for the feedback @mikesweeting!
